dbt_prj_rts_interview:
  outputs:
    dev:
      dataset: dts_rts_interview
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\ffarooq\repos\rts-interview\service_account_key.json
      location: europe-west9
      method: service-account
      priority: interactive
      project: prj-faiqabahra-rts-interview
      threads: 1
      type: bigquery
  target: dev
